# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=400)),
                ('director', models.CharField(max_length=50)),
                ('num_rooms', models.IntegerField()),
                ('energy_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.FloatField()),
                ('power', models.FloatField()),
                ('time_delta', models.FloatField()),
                ('dorm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.Dorm')),
            ],
        ),
    ]
