# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyreading',
            name='time_delta',
        ),
        migrations.AddField(
            model_name='energyreading',
            name='time_delta_ms',
            field=models.FloatField(default=1000),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='energy_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='num_rooms',
            field=models.IntegerField(default=0),
        ),
    ]
