# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-30 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20170913_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=400)),
                ('num_rooms', models.IntegerField(default=0)),
                ('energy_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=400)),
                ('num_rooms', models.IntegerField(default=0)),
                ('energy_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=400)),
                ('num_rooms', models.IntegerField(default=0)),
                ('energy_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=400)),
                ('num_rooms', models.IntegerField(default=0)),
                ('energy_score', models.IntegerField(default=0)),
            ],
        ),
    ]
